#
# show all motions with 3 sec interval
#
${interval}="3.0"

0 START:
    <eps> MODEL_ADD|0|../MS_Uka.pmd
    MODEL_EVENT_ADD|0 MOTION_ADD|0|base|stand.vmd|FULL|LOOP
    MOTION_EVENT_ADD|0|base TEXTAREA_ADD|name|0,2.4|1,1,1|0,0,0,0.6|1,1,1,1|0,16,4
    TEXTAREA_EVENT_ADD|name CAMERA|0,18,0|0,0,0|36|16

START END:
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|01_happy.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|01_happy
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|02_laugh.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|02_laugh
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|03_smile.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|03_smile
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|04_littlesmile.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|04_littlesmile
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|05_gracefulsmile.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|05_gracefulsmile
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|06_embarassedsmile.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|06_embarassedsmile
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|07_annoyedsmile.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|07_annoyedsmile
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|08_surprise.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|08_surprise
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|09_unexpected.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|09_unexpected
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|10_impressed.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|10_impressed
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|11_admiration.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|11_admiration
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|12_expectant.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|12_expectant
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|13_convinced.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|13_convinced
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|14_crisp.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|14_crisp
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|15_proud.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|15_proud
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|16_thinking.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|16_thinking
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|17_nothankyou.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|17_nothankyou
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|18_compassion.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|18_compassion
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|19_triumphant.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|19_triumphant
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|20_introuble.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|20_introuble
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|21_disgust.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|21_disgust
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|22_apology.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|22_apology
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|23_stressed.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|23_stressed
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|24_embarrasing.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|24_embarrasing
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|25_sharpeyessuspicion.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|25_sharpeyessuspicion
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|26_mortifying.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|26_mortifying
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|27_provoking.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|27_provoking
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|28_sleepy.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|28_sleepy
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|29_Terrified.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|29_Terrified
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|30_stunned.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|30_stunned
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|31_disappointed.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|31_disappointed
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|32_frustrated.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|32_frustrated
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|33_angry.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|33_angry
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|34_sad.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|34_sad
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|35_Afraid.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|35_Afraid
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|36_Anxious.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|36_Anxious
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|37_Sentimental.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|37_Sentimental
    <eps> TIMER_START|w|${interval}
    TIMER_EVENT_STOP|w MOTION_ADD|0|action|38_Ashamed.vmd|PART|ONCE
    <eps> TEXTAREA_SET|name|38_Ashamed
